const Country = [
  "Afghanistan",
     "Albania",
     "Algeria",
     "Andorra",
     "Angola",
     "Antigua and Barbuda",
     "Argentina",
     "Armenia",
     "Australia",
     "Austria",
     "Azerbaijan",
     "Bahamas",
     "Bahrain",
     "Bangladesh",
     "Barbados",
     "Belarus",
     "Belgium",
     "Belize",
     "Benin",
     "Bhutan",
     "Bolivia",
     "Bosnia and Herzegovina",
     "Botswana",
     "Brazil",
     "Brunei",
     "Bulgaria",
     "Burkina Faso",
     "Burundi",
     "Cabo Verde",
     "Cambodia",
     "Cameroon",
     "Canada",
     "Central African Republic",
     "Chad",
     "Chile",
     "China",
     "Colombia",
     "Comoros",
     "Congo (Congo-Brazzaville)",
     "Costa Rica",
     "Croatia",
     "Cuba",
     "Cyprus",
     "Czechia (Czech Republic)",
     "Democratic Republic of the Congo",
     "Denmark",
     "Djibouti",
     "Dominica",
     "Dominican Republic",
     "Ecuador",
     "Egypt",
     "El Salvador",
     "Equatorial Guinea",
     "Eritrea",
     "Estonia",
     "Eswatini (fmr. 'Swaziland')",
     "Ethiopia",
     "Fiji",
     "Finland",
     "France",
     "Gabon",
     "Gambia",
     "Georgia",
     "Germany",
     "Ghana",
     "Greece",
     "Grenada",
     "Guatemala",
     "Guinea",
     "Guinea-Bissau",
     "Guyana",
     "Haiti",
     "Honduras",
     "Hungary",
     "Iceland",
     "India",
     "Indonesia",
     "Iran",
     "Iraq",
     "Ireland",
     "Israel",
     "Italy",
     "Ivory Coast",
     "Jamaica",
     "Japan",
     "Jordan",
     "Kazakhstan",
     "Kenya",
     "Kiribati",
     "Kuwait",
     "Kyrgyzstan",
     "Laos",
     "Latvia",
     "Lebanon",
     "Lesotho",
     "Liberia",
     "Libya",
     "Liechtenstein",
     "Lithuania",
     "Luxembourg",
     "Madagascar",
     "Malawi",
     "Malaysia",
     "Maldives",
     "Mali",
     "Malta",
     "Marshall Islands",
     "Mauritania",
     "Mauritius",
     "Mexico",
     "Micronesia",
     "Moldova",
     "Monaco",
     "Mongolia",
     "Montenegro",
     "Morocco",
     "Mozambique",
     "Myanmar (Burma)",
     "Namibia",
     "Nauru",
     "Nepal",
     "Netherlands",
     "New Zealand",
     "Nicaragua",
     "Niger",
     "Nigeria",
     "North Korea",
     "North Macedonia",
     "Norway",
     "Oman",
     "Pakistan",
     "Palau",
     "Palestine",
     "Panama",
     "Papua New Guinea",
     "Paraguay",
     "Peru",
     "Philippines",
     "Poland",
     "Portugal",
     "Qatar",
     "Romania",
     "Russia",
     "Rwanda",
     "Saint Kitts and Nevis",
     "Saint Lucia",
     "Saint Vincent and the Grenadines",
     "Samoa",
     "San Marino",
     "Sao Tome and Principe",
     "Saudi Arabia",
     "Senegal",
     "Serbia",
     "Seychelles",
     "Sierra Leone",
     "Singapore",
     "Slovakia",
     "Slovenia",
     "Solomon Islands",
     "Somalia",
     "South Africa",
     "South Korea",
     "South Sudan",
     "Spain",
     "Sri Lanka",
     "Sudan",
     "Suriname",
     "Sweden",
     "Switzerland",
     "Syria",
     "Tajikistan",
     "Tanzania",
     "Thailand",
     "Timor-Leste",
     "Togo",
     "Tonga",
     "Trinidad and Tobago",
     "Tunisia",
     "Turkey",
     "Turkmenistan",
     "Tuvalu",
     "Uganda",
     "Ukraine",
     "United Arab Emirates",
     "UK",
     "USA",
     "Uruguay",
     "Uzbekistan",
     "Vanuatu",
     "Vatican City",
     "Venezuela",
     "Vietnam",
     "Yemen",
     "Zambia",
     "Zimbabwe",
 ];

 const Global_hq = [
  "Afghanistan",
     "Albania",
     "Algeria",
     "Andorra",
     "Angola",
     "Antigua and Barbuda",
     "Argentina",
     "Armenia",
     "Australia",
     "Austria",
     "Azerbaijan",
     "Bahamas",
     "Bahrain",
     "Bangladesh",
     "Barbados",
     "Belarus",
     "Belgium",
     "Belize",
     "Benin",
     "Bhutan",
     "Bolivia",
     "Bosnia and Herzegovina",
     "Botswana",
     "Brazil",
     "Brunei",
     "Bulgaria",
     "Burkina Faso",
     "Burundi",
     "Cabo Verde",
     "Cambodia",
     "Cameroon",
     "Canada",
     "Central African Republic",
     "Chad",
     "Chile",
     "China",
     "Colombia",
     "Comoros",
     "Congo (Congo-Brazzaville)",
     "Costa Rica",
     "Croatia",
     "Cuba",
     "Cyprus",
     "Czechia (Czech Republic)",
     "Democratic Republic of the Congo",
     "Denmark",
     "Djibouti",
     "Dominica",
     "Dominican Republic",
     "Ecuador",
     "Egypt",
     "El Salvador",
     "Equatorial Guinea",
     "Eritrea",
     "Estonia",
     "Eswatini (fmr. 'Swaziland')",
     "Ethiopia",
     "Fiji",
     "Finland",
     "France",
     "Gabon",
     "Gambia",
     "Georgia",
     "Germany",
     "Ghana",
     "Greece",
     "Grenada",
     "Guatemala",
     "Guinea",
     "Guinea-Bissau",
     "Guyana",
     "Haiti",
     "Honduras",
     "Hungary",
     "Iceland",
     "India",
     "Indonesia",
     "Iran",
     "Iraq",
     "Ireland",
     "Israel",
     "Italy",
     "Ivory Coast",
     "Jamaica",
     "Japan",
     "Jordan",
     "Kazakhstan",
     "Kenya",
     "Kiribati",
     "Kuwait",
     "Kyrgyzstan",
     "Laos",
     "Latvia",
     "Lebanon",
     "Lesotho",
     "Liberia",
     "Libya",
     "Liechtenstein",
     "Lithuania",
     "Luxembourg",
     "Madagascar",
     "Malawi",
     "Malaysia",
     "Maldives",
     "Mali",
     "Malta",
     "Marshall Islands",
     "Mauritania",
     "Mauritius",
     "Mexico",
     "Micronesia",
     "Moldova",
     "Monaco",
     "Mongolia",
     "Montenegro",
     "Morocco",
     "Mozambique",
     "Myanmar (Burma)",
     "Namibia",
     "Nauru",
     "Nepal",
     "Netherlands",
     "New Zealand",
     "Nicaragua",
     "Niger",
     "Nigeria",
     "North Korea",
     "North Macedonia",
     "Norway",
     "Oman",
     "Pakistan",
     "Palau",
     "Palestine",
     "Panama",
     "Papua New Guinea",
     "Paraguay",
     "Peru",
     "Philippines",
     "Poland",
     "Portugal",
     "Qatar",
     "Romania",
     "Russia",
     "Rwanda",
     "Saint Kitts and Nevis",
     "Saint Lucia",
     "Saint Vincent and the Grenadines",
     "Samoa",
     "San Marino",
     "Sao Tome and Principe",
     "Saudi Arabia",
     "Senegal",
     "Serbia",
     "Seychelles",
     "Sierra Leone",
     "Singapore",
     "Slovakia",
     "Slovenia",
     "Solomon Islands",
     "Somalia",
     "South Africa",
     "South Korea",
     "South Sudan",
     "Spain",
     "Sri Lanka",
     "Sudan",
     "Suriname",
     "Sweden",
     "Switzerland",
     "Syria",
     "Tajikistan",
     "Tanzania",
     "Thailand",
     "Timor-Leste",
     "Togo",
     "Tonga",
     "Trinidad and Tobago",
     "Tunisia",
     "Turkey",
     "Turkmenistan",
     "Tuvalu",
     "Uganda",
     "Ukraine",
     "United Arab Emirates",
     "UK",
     "USA",
     "Uruguay",
     "Uzbekistan",
     "Vanuatu",
     "Vatican City",
     "Venezuela",
     "Vietnam",
     "Yemen",
     "Zambia",
     "Zimbabwe",
 ];
 
 const industries = [
  "AI and ML",
  "API",
  "AR/VR",
  "Analytics",
  "Automation",
  "Biotech",
  "Cloud",
  "Crypto/Blockchain",
  "Deep Tech/Hard Science",
  "Developer Tools",
  "IoT",
  "Robotics",
  "SaaS",
  "Adtech",
  "Aerospace",
  "Agritech",
  "Apparel & Fashion",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Broadcast Media",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Climate/Sustainability",
  "Construction",
  "Consumer",
  "Consumer Electronics",
  "Consumer Goods",
  "Cosmetics",
  "Cyber Security",
  "Defense & Space",
  "Design",
  "Diagnostics",
  "DNA/RNA",
  "DTC",
  "Ecommerce",
  "Edtech",
  "Electrical/Electronic Manufacturing",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Fintech",
  "Food & Beverage",
  "Freight",
  "Future of Work",
  "Gaming",
  "Government Technology",
  "Greentech",
  "Hardware",
  "Hardtech",
  "Health and Wellness",
  "Healthcare/Medtech",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Industrial",
  "InsureTech",
  "Insurance",
  "Internet and Mobile",
  "JusticeTech",
  "K-12",
  "Language Learning",
  "Legal Services",
  "Leisure, Travel & Tourism",
  "Life Sciences",
  "Logistics & Supply Chain",
  "Management Consulting",
  "Manufacturing & Automation",
  "Market Research",
  "Marketplace",
  "Marketing & Advertising",
  "Materials",
  "Media",
  "Media Production",
  "Medical Devices",
  "Mental Health",
  "Mobility",
  "Music",
  "-omics",
  "Online Media",
  "Optics, Photonics",
  "Outsourcing/Offshoring",
  "Payments",
  "Personal Finance",
  "Pharmaceuticals",
  "Pharma & Healthtech",
  "Philanthropy",
  "Primary/Secondary Education",
  "Productivity",
  "Program Development",
  "Proptech/Real Estate",
  "Proteins",
  "Public Relations & Communications",
  "Publishing",
  "Real Estate",
  "Recruiting",
  "Renewables & Environment",
  "Retail",
  "Revenue-Generating Startups",
  "Sales Enablement",
  "Security & Investigations",
  "Semiconductors",
  "Social",
  "Space",
  "Sports",
  "Staffing & Recruiting",
  "Supply Chain/Logistics",
  "Telecommunications",
  "Therapeutics",
  "Transportation",
  "Travel/Hospitality",
  "Travel/Tourism",
  "Vaccines",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Wellness",
  "Wholesale",
  "Wireless",
  "B2B",
  "B2C",
  "D2C",
"Sector Agnostic"
]
 
 const investorType = [
  "VC",
  "Family Office",
  "PE Fund",
  "Incubator, Accelerator",
  "Corporate VC",
  "Solo Angel",
  "Angel Network",
  "Public fund",
  "Revenue-Based",
  "Startup Studio",
  "Seed fund",
  "Multi-stage VC",
  "Solo capitalist",
  "Full-time Operator",
  "Angel"
];
 

 
 const previousFunding = ["Idea", "Prototype/MVP", "Pre-seed", "Seed", "Series+", "Series++", "Pre-IPO", "Post Revenue"]
 
 const requiredFunding = [
   "< $100K",
   "$100K - $500K",
   "$500K - $1M",
   "$1M - $5M",
   ">$5M"]


 //  const 
//  currentTraction = [
//    "PRE PRODUCTION LAUNCH",
//    "PRE REVENUE",
//    "POST REVENUE",
//    "BREAKEVEN"
//  ];

 export {
   Country,
   industries,
   investorType,
   Global_hq,
  //  currentTraction,
   previousFunding,
   requiredFunding,
 };