const Country = [
 "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. 'Swaziland')",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe",
];

const industries = [
  "AUTOMOTIVE", "BANKING", "BROADCAST MEDIA", "COMPUTER & NETWORK SECURITY", "COMPUTER SOFTWARE",
  "CONSUMER ELECTRONICS", "CONSUMER GOODS", "CONSUMER SERVICES", "CIVIC & SOCIAL ORGANIZATION",
  "DEFENSE & SPACE", "EDUCATION MANAGEMENT", "ENTERTAINMENT", "E-LEARNING", "FINANCIAL SERVICES",
  "FOOD & BEVERAGES", "HEALTH", "HIGHER EDUCATION", "HOSPITAL & HEALTH CARE", "HUMAN RESOURCES",
  "INSURANCE", "INFORMATION TECHNOLOGY & SERVICES", "INTERNET", "INVESTMENT MANAGEMENT",
  "LEGAL SERVICES", "LEISURE", "LOGISTICS & SUPPLY CHAIN", "MANAGEMENT CONSULTING",
  "MARKETING & ADVERTISING", "MEDIA PRODUCTION", "NONPROFIT ORGANIZATION MANAGEMENT",
  "ONLINE MEDIA", "OUTSOURCING/OFFSHORING", "PROFESSIONAL TRAINING & COACHING",
  "PUBLIC RELATIONS & COMMUNICATIONS", "REAL ESTATE", "RETAIL", "STAFFING & RECRUITING",
  "TRANSLATION & LOCALIZATION", "VENTURE CAPITAL & PRIVATE EQUITY", "WELLNESS & FITNESS",
  "TRAVEL"
];

const investorType = [
  "AGTECH", "ARTIFICIAL INTELLIGENCE", "ARTIFICIAL REALITY", "AUTOMATION", "BANKING", "BIOTECH",
  "BLOCKCHAIN", "CLOUD COMPUTING", "CONSUMER ELECTRONICS", "CONSUMER GOODS", "CONSUMER INTERNET",
  "CONSUMER SERVICES", "CRYPTOCURRENCY", "DATA ANALYTICS", "DIGITAL HEALTH", "DIGITAL MEDIA",
  "DIGITAL TRANSFORMATION", "E-COMMERCE", "EDUCATION", "EDTECH", "ENTERPRISE SOFTWARE",
  "FASHION", "FINANCIAL SERVICES", "FOOD & BEVERAGE", "FOODTECH", "GAMING", "GOVTECH",
  "HEALTHCARE", "HEALTHTECH", "HARDWARE", "HOSPITALITY", "HUMAN RESOURCES", "INSURTECH",
  "INTERNET", "INTERNET OF THINGS (IOT)", "INVESTMENT MANAGEMENT", "LEGAL SERVICES",
  "LEGALTECH", "LOGISTICS", "MARKETPLACE", "MARKETING TECHNOLOGY", "MOBILE", "NONPROFIT",
  "NEUROTECH", "ONLINE MEDIA", "PROPTECH", "PUBLIC RELATIONS & COMMUNICATIONS", "REAL ESTATE",
  "REGTECH", "RETAIL", "ROBOTICS", "SAAS", "SECURITY", "SOCIAL NETWORK", "SUSTAINABILITY",
  "SUSTAINABILITY TECH", "TELECOMMUNICATIONS", "TRANSPORTATION", "TRAVEL",
  "VENTURE CAPITAL & PRIVATE EQUITY", "VIRTUAL REALITY", "WEB3"
];

const 
currentTraction = [
  "PRE PRODUCTION LAUNCH",
  "PRE REVENUE",
  "POST REVENUE",
  "BREAKEVEN"
];

const previousFunding = [
  "BOOTSTRAPPED",
  "ANGEL INVESTMENT",
  "PRE SEED",
  "SEED",
  "PRE SERIES",
  "SERIES A+"
];

const requiredFunding = [
  "< $100K",
  "$100K - $500K",
  "$500K - $1M",
  "$1M - $5M",
  ">$5M"]

export {
  Country,
  industries,
  investorType,
  currentTraction,
  previousFunding,
  requiredFunding,
};